/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Stats on garbage collection
 */
export interface StatsProcGc { 
    /**
     * Memory allocation speed
     */
    allocationSpeed?: number;
    /**
     * Number of generation 0 garbage collections
     */
    gen0ItemsCount?: number;
    /**
     * Generation 0 heap size
     */
    gen0Size?: number;
    /**
     * Number of generation 1 garbage collections
     */
    gen1ItemsCount?: number;
    /**
     * Generation 1 heap size
     */
    gen1Size?: number;
    /**
     * Number of generation 2 garbage collections
     */
    gen2ItemsCount?: number;
    /**
     * Generation 2 heap size
     */
    gen2Size?: number;
    /**
     * Large object heap size
     */
    largeHeapSize?: number;
    /**
     * Percentage of time in garbage collection
     */
    timeInGc?: number;
    /**
     * Total bytes in all heaps
     */
    totalBytesInHeaps?: number;
}

