/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatsEsWriter } from './statsEsWriter';
import { StatsEsReadIndex } from './statsEsReadIndex';
import { StatsEsQueue } from './statsEsQueue';


/**
 * 
 */
export interface StatsEs { 
    /**
     * 
     */
    checksum?: number;
    /**
     * 
     */
    checksumNonFlushed?: number;
    queue?: StatsEsQueue;
    writer?: StatsEsWriter;
    readIndex?: StatsEsReadIndex;
}

