/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatsSysDriveDriveName } from './statsSysDriveDriveName';


/**
 * Drive usage stats
 */
export interface StatsSysDrive { 
    driveName?: StatsSysDriveDriveName;
}

