/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Storage writing stats
 */
export interface StatsEsWriter { 
    /**
     * Last flush size
     */
    lastFlushSize?: number;
    /**
     * Last flush delay in ms
     */
    lastFlushDelayMs?: number;
    /**
     * Average flush size
     */
    meanFlushSize?: number;
    /**
     * Average flush delay in ms
     */
    meanFlushDelayMs?: number;
    /**
     * Max flush size
     */
    maxFlushSize?: number;
    /**
     * Max flush delay in ms
     */
    maxFlushDelayMs?: number;
    /**
     * Queued flush messages
     */
    queuedFlushMessages?: number;
}

