/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatsProc } from './statsProc';
import { StatsEs } from './statsEs';
import { StatsSys } from './statsSys';


export interface Stats { 
    proc?: StatsProc;
    sys?: StatsSys;
    es?: StatsEs;
}

