/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Multiple queue instance stats
 */
export interface StatsEsQueue { 
    /**
     * Queue name
     */
    queueName?: string;
    /**
     * Group queue is a member of
     */
    groupName?: string;
    /**
     * The average number of items processed per second by the queue
     */
    avgItemsPerSecond?: number;
    /**
     * Average number of items processed per second
     */
    avgProcessingTime?: number;
    /**
     * Time elapsed since queue went idle
     */
    currentIdleTime?: string;
    /**
     * Time elapsed processing the current item
     */
    currentItemProcessingTime?: string;
    /**
     * Percentage of time queue spent idle
     */
    idleTimePercent?: number;
    /**
     * Number of items in the queue
     */
    length?: number;
    /**
     * The highest number of items in the queue within the past 100ms
     */
    lengthCurrentTryPeak?: number;
    /**
     * The highest number of items in the queue
     */
    lengthLifetimePeak?: number;
    /**
     * The total number of items processed by the queue
     */
    totalItemsProcessed?: number;
    /**
     * Current message type queue is processing
     */
    inProgressMessage?: string;
    /**
     * Last message type processed
     */
    lastProcessedMessage?: string;
}

