/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface StatsEsReadIndex { 
    /**
     * Number of cached record reads
     */
    cachedRecord?: number;
    /**
     * Number of uncached record reads
     */
    notCachedRecord?: number;
    /**
     * 
     */
    cachedStreamInfo?: number;
    /**
     * 
     */
    notCachedStreamInfo?: number;
    /**
     * 
     */
    cachedTransInfo?: number;
    /**
     * 
     */
    notCachedTransInfo?: number;
    /**
     * 
     */
    hashCollisions?: number;
}

