/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatsSysDrive } from './statsSysDrive';


/**
 * System usage stats
 */
export interface StatsSys { 
    /**
     * Total CPU usage in percentage
     */
    cpu?: number;
    /**
     * Free memory in bytes
     */
    freeMem?: number;
    drive?: StatsSysDrive;
}

