/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Drive path
 */
export interface StatsSysDriveDriveName { 
    /**
     * Remaining bytes of space available to Event Store
     */
    availableBytes?: number;
    /**
     * Total bytes of space available to Event Store
     */
    totalBytes?: number;
    /**
     * Percentage usage of space used by Event Store
     */
    usage?: number;
    /**
     * Total bytes of space used by Event Store
     */
    usedBytes?: number;
}

