/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Access control list for this stream
 */
export interface StreamMetadataItemDataAcl { 
    /**
     * Read roles
     */
    r?: string;
    /**
     * Write roles
     */
    w?: string;
    /**
     * Delete roles
     */
    d?: string;
    /**
     * Metadata read roles
     */
    mr?: string;
    /**
     * Metadata write roles
     */
    mw?: string;
}

