/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StreamMetadataItemData } from './streamMetadataItemData';


export interface StreamMetadataItem { 
    /**
     * Alphanumeric ID
     */
    eventId?: string;
    /**
     * The type of event
     */
    eventType?: string;
    data?: StreamMetadataItemData;
}

