/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * OpenAPI spec version: 4.1.1
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StreamMetadataItemData } from './streamMetadataItemData';


export interface StreamMetadataItem { 
    /**
     * Alphanumeric ID
     */
    eventId?: string;
    /**
     * The type of event
     */
    eventType?: string;
    data?: StreamMetadataItemData;
}
