/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StreamMetadataItemDataAcl } from './streamMetadataItemDataAcl';


export interface StreamMetadataItemData { 
    /**
     * The maximum age of events in the stream
     */
    maxAge?: number;
    /**
     * The maximum count of events in the stream
     */
    maxCount?: number;
    /**
     * Events prior to this event are truncated and removed
     */
    truncateBefore?: number;
    /**
     * Period of time to make feed head cacheable
     */
    cacheControl?: string;
    acl?: StreamMetadataItemDataAcl;
}

