/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * OpenAPI spec version: 4.1.1
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserUpdateItem { 
    /**
     * The full name of the new user.
     */
    FullName?: string;
    /**
     * The groups the new user should become a member of.
     */
    Groups?: Array<string>;
}
