/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * OpenAPI spec version: 4.1.1
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserItem { 
    /**
     * The new users login name.
     */
    LoginName?: string;
    /**
     * The full name for the new user.
     */
    FullName?: string;
    /**
     * The groups the new user is a member of.
     */
    Groups?: Array<string>;
    /**
     * The password for the new user.
     */
    Password?: string;
}
