/**
 * HTTP API
 * The HTTP API for Event Store
 *
 * The version of the OpenAPI document: 5.0.4
 * Contact: chris.ward@eventstore.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserItem { 
    /**
     * The new users login name.
     */
    loginName?: string;
    /**
     * The full name for the new user.
     */
    fullName?: string;
    /**
     * The groups the new user is a member of.
     */
    groups?: Array<string>;
    /**
     * The password for the new user.
     */
    password?: string;
}

